-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_REPLY r INNER JOIN USED_GOODS_BOARD b ON r.BOARD_ID = b.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE,'%Y%m') = 202210
    AND B.BOARD_ID = R.BOARD_ID
ORDER BY r.CREATED_DATE, b.TITLE;
